### ISSUE TITLE
Mandatory fields not signalized with an asterisk

### ISSUE THREAD

**Issue by basicavisual** [okfn-brasil/minutas#24]
Within the decidim demo on demo.decidim.org the fields for new participatory process are marked by asterisk when they are mandatory but not on our version. Screenshots:

demo.decidim.org

![image](https://github.com/okfn-brasil/minutas/assets/8941178/1f001203-492a-4ffe-9493-09b2e6301c9f)

minutas.okbr.org

![image](https://github.com/okfn-brasil/minutas/assets/8941178/4e62a2f7-b0fb-4fd5-8d95-d1ca28edbfcf)

**Comment by ghost** [comment]
Couldn't reproduce the issue on my development environment: `/admin/participatory_processes/new`

<img width="800" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/b758a098-3d2c-4468-9022-7258b7c7577f">

Its rendering process follows: [controller] → ([form builder] ← [form]) → ... `view`

Fields on a form are _required_ whenever there's a validator bound to them. [^1]

From a quick glance (`git log --patch`), it looks like there have been no significant changes, so we might be talking about different views. 😅

Do you have more details, @basicavisual ?



[controller]:  https://github.com/decidim/decidim/blob/d15dcd6e7b073aaa53d985636969f27bd0b606c3/decidim-participatory_processes/app/controllers/decidim/participatory_processes/admin/participatory_processes_controller.rb#L28-L31

[form]: https://github.com/decidim/decidim/blob/develop/decidim-participatory_processes/app/forms/decidim/participatory_processes/admin/participatory_process_form.rb

[form builder]: https://github.com/decidim/decidim/blob/d15dcd6e7b073aaa53d985636969f27bd0b606c3/decidim-core/lib/decidim/form_builder.rb

[^1]: https://github.com/decidim/decidim/blob/d15dcd6e7b073aaa53d985636969f27bd0b606c3/decidim-core/lib/decidim/form_builder.rb#L608-L625

**Comment by ghost** [comment]
@categulario , is production currently running from the latest release (commit) of the project?

**Comment by categulario** [comment]
no, but let's change that

**Comment by categulario** [comment]
Done

**Comment by ghost** [comment]
Thanks, @categulario !
@basicavisual , can you confirm that the issue is still present?

**Comment by ghost** [comment]
This might be related to fields not being recognized as `translatable`.

**Comment by ghost** [comment]
Taking a look with more detail, I found that, when a Decidim instance is configured with only one locale (the case of `cominutas`), it doesn't render the `translatable_attributes` as required. [^1]

I couldn't replicate it before because the `bin/rails db:seed` (used as well by the demo) sets an organization with multiple locales.

It can be solved by a small change on the [form](https://github.com/decidim/decidim/blob/83be368eb17d4a1b77512dbb59ed2bff04e40246/decidim-participatory_processes/app/views/decidim/participatory_processes/admin/participatory_processes/_form.html.erb) partial.

I would consider sending the patch to upstream.

[^1]: https://github.com/decidim/decidim/blob/83be368eb17d4a1b77512dbb59ed2bff04e40246/decidim-core/lib/decidim/form_builder.rb#L64-L95

**Comment by ghost** [comment]
Here's a screenshot from my `localhost` after the patch:

<img width="1037" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/ffde39a3-122e-42a8-9bf2-f9d0eb0602ac">

**Comment by ghost** [comment]
Just to be noted, this problem is also present on the assemblies form.

<img width="1044" alt="image" src="https://github.com/okfn-brasil/minutas/assets/141537607/034a78a7-1868-468b-88e0-01fd40369100">

**Comment by ghost** [comment]
Couldn't find a way to patch the `form.translated :edtior`, it deletes the `required: true` even if hardcoded. [^1]

To fix this, the only way I'm thinking about it right now, would require to patch `form_builder` upstream.

[^1]: https://github.com/decidim/decidim/blob/release/0.27-stable/decidim-core/lib/decidim/form_builder.rb#L192

**Comment by categulario** [comment]
what about just configuring the deployment to have more than one locale?

**Comment by ghost** [comment]
Thanks for reviewing this issue, @categulario.

> what about just configuring the deployment to have more than one locale?

That might work, indeed.
However, it would display a dropdown for selecting the label (it might be an inconvenience).
